name: Build-OpenWrt

on:
  workflow_dispatch:
  push:
    branches:
      - master
#  schedule:
#    - cron: 0 16 * * *

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    #    timeout-minutes: 360

    steps:
      - name: Clone Repository
        uses: actions/checkout@v2

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: false
  
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: true
          swap-storage: true

      - name: Init Compilation Dependencies
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          curl -sL https://build-scripts.immortalwrt.eu.org/init_build_environment.sh | sudo bash

      - name: Check space
        if: (!cancelled())
        run: df -hT

      - name: Clone Source
        run: |
          cd /home/runner
          bash ${GITHUB_WORKSPACE}/clone_source.sh
          sudo chown -R runner:runner openwrt

      - name: Before Build
        run: |
          bash ${GITHUB_WORKSPACE}/before_build.sh

      - name: Start Build
        run: |
          cd /home/runner/openwrt
          rm -f .config*
          cp ${GITHUB_WORKSPACE}/.config /home/runner/openwrt
          make defconfig
          cat .config
          make -j$[$(nproc)+1]

      - name: After Build
        run: |
          bash ${GITHUB_WORKSPACE}/after_build.sh

      - name: Upload Packages
        uses: actions/upload-artifact@v4
        with:
          name: Packages
          path: /home/runner/openwrt/bin/packages/

      - name: Upload Firmwares
        uses: actions/upload-artifact@v4
        with:
          name: Firmwares
          path: /home/runner/openwrt/bin/targets/
